# This workflow deploys the full site to multiple test environments using a matrix.
# Each environment deployment depends on the one before it completing successfully.
# The environments are:
# - dev
# - test
# - qa
# - staging
# - preprod
# - prod

name: Matrix Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Simulate build
        run: |
          echo "Building site..."
          touch build_output.txt
          echo "Build complete."
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact
          path: ./build_output.txt
  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to dev
        run: |
          echo "Deploying to dev..."
          ./deploy.sh dev
  deploy_test:
    runs-on: ubuntu-latest
    needs: deploy_dev
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to test
        run: |
          echo "Deploying to test..."
          ./deploy.sh test

  deploy_qa:
    runs-on: ubuntu-latest
    needs: deploy_test
    environment: qa
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to qa
        run: |
          echo "Deploying to qa..."
          ./deploy.sh qa

  deploy_staging:
    runs-on: ubuntu-latest
    needs: deploy_qa
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to staging
        run: |
          echo "Deploying to staging..."
          ./deploy.sh staging

  deploy_preprod:
    runs-on: ubuntu-latest
    needs: deploy_staging
    environment: preprod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to preprod
        run: |
          echo "Deploying to preprod..."
          ./deploy.sh preprod

  deploy_production:
    runs-on: ubuntu-latest
    needs: deploy_preprod
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          ./deploy.sh production
