# This workflow deploys the full site to multiple test environments using a matrix.
# Each environment deployment depends on the one before it completing successfully.
# The environments are:
# - dev
# - test
# - qa
# - staging
# - preprod
# - prod

name: Matrix Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Simulate build
        run: |
          echo "Building site..."
          touch build_output.txt
          echo "Build complete."
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact
          path: ./build_output.txt
  deploy_dev:
    needs: build
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: dev
  deploy_test:
    needs: deploy_dev
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: test

  deploy_qa:
    needs: deploy_test
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: qa

  deploy_staging:
    needs: deploy_qa
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: staging

  deploy_preprod:
    needs: deploy_staging
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: preprod

  deploy_production:
    needs: deploy_preprod
    uses: ./.github/workflows/reusable-deploy.yml
    with:
      environment: prod
