# This workflow deploys the full site to multiple test environments using a matrix.
# Each environment deployment depends on the one before it completing successfully.
# The environments are:
# - dev
# - test
# - qa
# - staging
# - preprod
# - production

name: Matrix Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Simulate build
        run: echo "Building site..." && sleep 5 && echo "Build complete."
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-artifact
  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, test, qa, staging, preprod]
    environment: ${{ matrix.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to ${{ matrix.environment }}
        run: |
          echo "Deploying to ${{ matrix.environment }} environment"
          ./deploy.sh ${{ matrix.environment }}
  prod-deploy:
    needs: deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: site-artifact
      - name: Deploy to production
        run: |
          echo "Deploying to production environment"
          ./deploy.sh production
